[package]
name = "bpr"
version = "0.2.0"
authors = ["Matt Lawlor <matt.a.lawlor@gmail.com>"]
edition = "2018"

[dependencies]
clap = {version = "~2.32.0", features = ["yaml"]}
rust-htslib = "0.22.0"
quick-error="1.2.2"
regex = "1"
itertools = "*"
rand = "0.6.1"
rand_xorshift = "0.1.0"
